### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by skyzyx** [opentofu/terraform-provider-go#1]
(Moving this out of Slack.)

Respectfully, although we _can_ do things like this, I’m not convinced we _should_ do things like this. I’ve spent some time thinking about this before, but since it basically comes down to executing loose code, I chose to take the time to learn the TPF and chose not to implement support for what is essentially `exec()`.

Too much opportunity for mis-use, for rogue modules, and this opens up doors for security vulnerabilities. Even more, making it easy for inexperienced people to make insecure decisions is always something to shy away from, IMO.

From an engineering standpoint, I think it’s a **very cool** technology demo. From a security and responsibility standpoint, it would be irresponsible of me to not push back. Without very clear outlines for what is “supported” (read: what we’re on the hook for) vs “unsupported” (read: what we are absolutely not on the hook for), this is a bit of a Pandora’s Box.

I look at this, and while I’m impressed by the creativity, I’m concerned by the new attack surface this creates.

I’m a strong believer in understanding what you’re shipping to production. Namely, not grabbing random packages off the internet and shipping them. But engineers with less experience often have no problem with this because they can’t see past “how do I make this work so that I can close my ticket.”

It is that group of users for whom I am most concerned. If someone were to wrap this provider in a module with some custom Go code for reading files from the file system and shipping them back to the attacker… what lengths does this provider take to prevent that kind of abuse?

I’m pushing back because I care. I think these are important questions, and we have a responsibility to our users/customers to protect them — sometimes from themselves.

**Comment by cube2222** [comment]
Note to others, this has been discussed on Slack: https://opentofucommunity.slack.com/archives/C05QF5HA0BH/p1713890013543989?thread_ts=1713797313.002699&cid=C05QF5HA0BH

TLDR is that OpenTofu already supports the local-exec provisioner, which is already much worse, as it's fairly transparent when planning/applying. While here you can verify the lockfile that you'll see changing in the PR, as the provider is needed.

Overall, with OpenTofu you already have to fully trust all your providers and modules, as they all have effectively unlimited access. Thus, we don't believe that this is introducing any new risks.

Now, whether this will encourage good config patterns is another question, but that's why we're introducing this as experimental first, and want to see the community's response to it.

**Comment by ghost** [comment]
As an added note I would like to add that the provider simply existing does not enable anything that the provider API itself doesn't. Anyone is free to make a provider that enables executing other code, or may itself contain nefarious code. One potential avenue to sandboxing providers would be opentofu/opentofu#1138, which I would encourage anyone with concerns around providers misbehaving to upvote.
